// AUTO-GENERATED by `npm run gen:zod`. Edit upstream OpenAPI instead.
// Zodios client stripped via scripts/strip-zodios-client.mjs.

import { z } from "zod";

const ValidationError = z
  .object({
    loc: z.array(z.union([z.string(), z.number()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.object({}).partial().passthrough().optional(),
  })
  .passthrough();
const HTTPValidationError = z
  .object({ detail: z.array(ValidationError) })
  .partial()
  .passthrough();
const Body_upload_host_image_api_upload_host_image_post = z
  .object({ file: z.string() })
  .passthrough();
const Body_upload_background_image_api_upload_background_image_post = z
  .object({ file: z.string() })
  .passthrough();
const Body_upload_reference_image_api_upload_reference_image_post = z
  .object({ file: z.string() })
  .passthrough();
const Body_preview_composite_api_preview_composite_post = z
  .object({
    host_image_path: z.string(),
    bg_image_path: z.string(),
    resolution: z.string().optional().default("1280x720"),
    scale: z.number().optional().default(0.7),
    position: z.string().optional().default("center"),
  })
  .passthrough();
const Body_preview_composite_together_api_preview_composite_together_post = z
  .object({
    host_image_paths: z.string(),
    resolution: z.string().optional().default("1280x720"),
    layout: z.string().optional().default("split"),
    scene_prompt: z.string().optional().default(""),
    reference_image_paths: z.string().optional().default("[]"),
  })
  .passthrough();
const Body_upload_reference_audio_api_upload_reference_audio_post = z
  .object({ file: z.string() })
  .passthrough();
const Body_upload_audio_api_upload_audio_post = z
  .object({ file: z.string() })
  .passthrough();
const Body_generate_elevenlabs_speech_api_elevenlabs_generate_post = z
  .object({
    text: z.string(),
    voice_id: z.string(),
    stability: z.number().optional().default(0.5),
    similarity_boost: z.number().optional().default(0.75),
    style: z.number().optional().default(0),
    speed: z.number().optional().default(1),
  })
  .passthrough();
const Body_clone_voice_api_elevenlabs_clone_voice_post = z
  .object({
    name: z.string(),
    file: z.string(),
    description: z.string().optional().default(""),
  })
  .passthrough();
const Body_generate_video_api_generate_post = z
  .object({
    audio_source: z.string().default("upload"),
    host_image_path: z.union([z.string(), z.null()]),
    audio_path: z.union([z.string(), z.null()]),
    script_text: z.string().default(""),
    voice_id: z.union([z.string(), z.null()]),
    stability: z.number().default(0.5),
    similarity_boost: z.number().default(0.75),
    style: z.number().default(0),
    prompt: z.union([z.string(), z.null()]),
    seed: z.number().int().default(9999),
    cpu_offload: z.boolean().default(true),
    resolution: z.string().default("1280x720"),
    scene_prompt: z.string().default(""),
    reference_image_paths: z.string().default("[]"),
    queue_label: z.union([z.string(), z.null()]),
    meta: z.union([z.string(), z.null()]),
    playlist_id: z.union([z.string(), z.null()]),
  })
  .partial()
  .passthrough();
const TaskStateSnapshot = z
  .object({
    task_id: z.string(),
    stage: z.union([z.string(), z.null()]).optional(),
    progress: z.union([z.number(), z.null()]).optional(),
    message: z.union([z.string(), z.null()]).optional(),
    error: z.union([z.string(), z.null()]).optional(),
    output_path: z.union([z.string(), z.null()]).optional(),
  })
  .passthrough();
const playlist_id = z.union([z.string(), z.null()]).optional();
const VideoHistoryItem = z
  .object({
    task_id: z.string(),
    timestamp: z.union([z.string(), z.null()]).optional(),
    type: z.union([z.enum(["generate", "conversation"]), z.null()]).optional(),
    status: z
      .union([z.enum(["completed", "error", "cancelled"]), z.null()])
      .optional(),
    public_error: z.union([z.string(), z.null()]).optional(),
    retried_from: z.union([z.string(), z.null()]).optional(),
    script_text: z.union([z.string(), z.null()]).optional(),
    host_image: z.union([z.string(), z.null()]).optional(),
    audio_source: z.union([z.string(), z.null()]).optional(),
    output_path: z.union([z.string(), z.null()]).optional(),
    file_size: z.union([z.number(), z.null()]).optional(),
    video_url: z.string(),
    generation_time: z.union([z.number(), z.null()]).optional(),
  })
  .passthrough();
const HistoryResponse = z
  .object({
    total: z.number().int(),
    videos: z.array(VideoHistoryItem).optional(),
  })
  .passthrough();
const Body_generate_conversation_endpoint_api_generate_conversation_post = z
  .object({
    dialog_data: z.string(),
    layout: z.string().optional().default("split"),
    prompt: z.union([z.string(), z.null()]).optional(),
    seed: z.number().int().optional().default(9999),
    cpu_offload: z.boolean().optional().default(true),
    resolution: z.string().optional().default("1280x720"),
    playlist_id: z.union([z.string(), z.null()]).optional(),
  })
  .passthrough();
const QueueEntry = z
  .object({
    task_id: z.string(),
    type: z.enum(["generate", "conversation"]),
    label: z.string().optional().default(""),
    status: z.enum(["pending", "running", "completed", "error", "cancelled"]),
    created_at: z.string(),
    started_at: z.union([z.string(), z.null()]).optional(),
    completed_at: z.union([z.string(), z.null()]).optional(),
    error: z.union([z.string(), z.null()]).optional(),
    params: z
      .union([z.object({}).partial().passthrough(), z.null()])
      .optional(),
  })
  .passthrough();
const QueueSnapshot = z
  .object({
    running: z.array(QueueEntry),
    pending: z.array(QueueEntry),
    recent: z.array(QueueEntry),
    total_running: z.number().int().default(0),
    total_pending: z.number().int().default(0),
  })
  .partial()
  .passthrough();
const ResultParams = z
  .object({
    host_image: z.union([z.string(), z.null()]),
    audio_path: z.union([z.string(), z.null()]),
    audio_source_label: z.union([z.string(), z.null()]),
    prompt: z.union([z.string(), z.null()]),
    seed: z.union([z.number(), z.null()]),
    cpu_offload: z.union([z.boolean(), z.null()]),
    script_text: z.union([z.string(), z.null()]),
    resolution_requested: z.union([z.string(), z.null()]),
    resolution_actual: z.union([z.string(), z.null()]),
    scene_prompt: z.union([z.string(), z.null()]),
    reference_image_paths: z.union([z.array(z.string()), z.null()]),
  })
  .partial()
  .passthrough();
const ResultManifest = z
  .object({
    task_id: z.string(),
    type: z.enum(["generate", "conversation"]).optional().default("generate"),
    status: z
      .enum(["completed", "error", "cancelled"])
      .optional()
      .default("completed"),
    created_at: z.union([z.string(), z.null()]).optional(),
    started_at: z.union([z.string(), z.null()]).optional(),
    completed_at: z.union([z.string(), z.null()]).optional(),
    generation_time_sec: z.union([z.number(), z.null()]).optional(),
    video_url: z.string(),
    video_path: z.union([z.string(), z.null()]).optional(),
    video_bytes: z.number().int().optional().default(0),
    video_filename: z.union([z.string(), z.null()]).optional(),
    params: ResultParams.optional(),
    meta: z.union([z.object({}).partial().passthrough(), z.null()]).optional(),
    error: z.union([z.string(), z.null()]).optional(),
    retried_from: z.union([z.string(), z.null()]).optional(),
    synthesized: z.boolean().optional().default(false),
  })
  .passthrough();
const Body_host_generate_api_host_generate_post = z
  .object({
    mode: z.string(),
    prompt: z.union([z.string(), z.null()]).optional(),
    extraPrompt: z.union([z.string(), z.null()]).optional(),
    negativePrompt: z.union([z.string(), z.null()]).optional(),
    builder: z.union([z.string(), z.null()]).optional(),
    faceRefPath: z.union([z.string(), z.null()]).optional(),
    outfitRefPath: z.union([z.string(), z.null()]).optional(),
    styleRefPath: z.union([z.string(), z.null()]).optional(),
    faceStrength: z.number().optional().default(0.7),
    outfitStrength: z.number().optional().default(0.7),
    outfitText: z.union([z.string(), z.null()]).optional(),
    seeds: z.union([z.string(), z.null()]).optional(),
    imageSize: z.string().optional().default("1K"),
    n: z.number().int().optional().default(4),
    temperature: z.union([z.number(), z.null()]).optional(),
  })
  .passthrough();
const Body_host_generate_stream_api_host_generate_stream_post = z
  .object({
    mode: z.string(),
    prompt: z.union([z.string(), z.null()]).optional(),
    extraPrompt: z.union([z.string(), z.null()]).optional(),
    negativePrompt: z.union([z.string(), z.null()]).optional(),
    builder: z.union([z.string(), z.null()]).optional(),
    faceRefPath: z.union([z.string(), z.null()]).optional(),
    outfitRefPath: z.union([z.string(), z.null()]).optional(),
    styleRefPath: z.union([z.string(), z.null()]).optional(),
    faceStrength: z.number().optional().default(0.7),
    outfitStrength: z.number().optional().default(0.7),
    outfitText: z.union([z.string(), z.null()]).optional(),
    seeds: z.union([z.string(), z.null()]).optional(),
    imageSize: z.string().optional().default("1K"),
    n: z.number().int().optional().default(4),
    temperature: z.union([z.number(), z.null()]).optional(),
  })
  .passthrough();
const Body_composite_generate_api_composite_generate_post = z
  .object({
    hostImagePath: z.string(),
    productImagePaths: z.string().optional().default("[]"),
    backgroundType: z.string(),
    backgroundPresetId: z.union([z.string(), z.null()]).optional(),
    backgroundPresetLabel: z.union([z.string(), z.null()]).optional(),
    backgroundUploadPath: z.union([z.string(), z.null()]).optional(),
    backgroundPrompt: z.union([z.string(), z.null()]).optional(),
    direction: z.string().optional().default(""),
    shot: z.string().optional().default("bust"),
    angle: z.string().optional().default("eye"),
    n: z.number().int().optional().default(4),
    temperature: z.union([z.number(), z.null()]).optional(),
    seeds: z.union([z.string(), z.null()]).optional(),
    imageSize: z.string().optional().default("1K"),
  })
  .passthrough();
const Body_composite_generate_stream_api_composite_generate_stream_post = z
  .object({
    hostImagePath: z.string(),
    productImagePaths: z.string().optional().default("[]"),
    backgroundType: z.string(),
    backgroundPresetId: z.union([z.string(), z.null()]).optional(),
    backgroundPresetLabel: z.union([z.string(), z.null()]).optional(),
    backgroundUploadPath: z.union([z.string(), z.null()]).optional(),
    backgroundPrompt: z.union([z.string(), z.null()]).optional(),
    direction: z.string().optional().default(""),
    shot: z.string().optional().default("bust"),
    angle: z.string().optional().default("eye"),
    n: z.number().int().optional().default(4),
    temperature: z.union([z.number(), z.null()]).optional(),
    seeds: z.union([z.string(), z.null()]).optional(),
    imageSize: z.string().optional().default("1K"),
  })
  .passthrough();
const SavedHostMeta = z
  .object({
    source: z.union([z.enum(["text", "image"]), z.null()]),
    selected_seed: z.union([z.number(), z.null()]),
    face_ref_storage_key: z.union([z.string(), z.null()]),
    outfit_ref_storage_key: z.union([z.string(), z.null()]),
    outfit_text: z.union([z.string(), z.null()]),
    prompt: z.union([z.string(), z.null()]),
    negative_prompt: z.union([z.string(), z.null()]),
    face_strength: z.union([z.number(), z.null()]),
    outfit_strength: z.union([z.number(), z.null()]),
  })
  .partial()
  .passthrough();
const SavedHost = z
  .object({
    id: z.string(),
    name: z.string(),
    key: z.string(),
    url: z.string(),
    created_at: z.union([z.string(), z.null()]).optional(),
    updated_at: z.union([z.string(), z.null()]).optional(),
    deleted_at: z.union([z.string(), z.null()]).optional(),
    meta: z.union([SavedHostMeta, z.null()]).optional(),
    face_ref_for_variation: z.string(),
  })
  .passthrough();
const SavedHostsListResponse = z
  .object({ hosts: z.array(SavedHost) })
  .partial()
  .passthrough();
const Body_save_host_api_hosts_save_post = z
  .object({
    source_image_id: z.string().min(1).max(128),
    name: z.string().min(1).max(100),
  })
  .passthrough();
const Body_create_playlist_api_playlists_post = z
  .object({ name: z.string() })
  .passthrough();
const Body_rename_playlist_api_playlists__playlist_id__patch = z
  .object({ name: z.string() })
  .passthrough();
const Body_move_result_to_playlist_api_results__task_id__playlist_patch = z
  .object({ playlist_id: z.union([z.string(), z.null()]) })
  .partial()
  .passthrough();
const Body_host_select_api_host_select_post = z
  .object({ image_id: z.string() })
  .passthrough();
const Body_composite_select_api_composite_select_post = z
  .object({ image_id: z.string() })
  .passthrough();

export const schemas = {
  ValidationError,
  HTTPValidationError,
  Body_upload_host_image_api_upload_host_image_post,
  Body_upload_background_image_api_upload_background_image_post,
  Body_upload_reference_image_api_upload_reference_image_post,
  Body_preview_composite_api_preview_composite_post,
  Body_preview_composite_together_api_preview_composite_together_post,
  Body_upload_reference_audio_api_upload_reference_audio_post,
  Body_upload_audio_api_upload_audio_post,
  Body_generate_elevenlabs_speech_api_elevenlabs_generate_post,
  Body_clone_voice_api_elevenlabs_clone_voice_post,
  Body_generate_video_api_generate_post,
  TaskStateSnapshot,
  playlist_id,
  VideoHistoryItem,
  HistoryResponse,
  Body_generate_conversation_endpoint_api_generate_conversation_post,
  QueueEntry,
  QueueSnapshot,
  ResultParams,
  ResultManifest,
  Body_host_generate_api_host_generate_post,
  Body_host_generate_stream_api_host_generate_stream_post,
  Body_composite_generate_api_composite_generate_post,
  Body_composite_generate_stream_api_composite_generate_stream_post,
  SavedHostMeta,
  SavedHost,
  SavedHostsListResponse,
  Body_save_host_api_hosts_save_post,
  Body_create_playlist_api_playlists_post,
  Body_rename_playlist_api_playlists__playlist_id__patch,
  Body_move_result_to_playlist_api_results__task_id__playlist_patch,
  Body_host_select_api_host_select_post,
  Body_composite_select_api_composite_select_post,
};
